# Generated by Django 3.2.7 on 2022-10-09 05:54

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Your name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+23481862329', max_length=30, verbose_name='Phone number')),
                ('email', models.EmailField(default='ijobra20@gmail.com', max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=100, verbose_name='Subkect')),
                ('message', models.TextField(verbose_name='Your message')),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
            },
        ),
    ]
