# Generated by Django 3.2.7 on 2022-10-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='desription',
            new_name='description',
        ),
    ]
