# Generated by Django 3.2.7 on 2022-10-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_desription_property_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='photo_1',
            new_name='photo1',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='photo_2',
            new_name='photo2',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='photo_3',
            new_name='photo3',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='photo_4',
            new_name='photo4',
        ),
    ]
